import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    containerGeral: {
        flex: 1,
        backgroundColor: '#384252',
        alignItems: 'center',
    },
    header: {
        width: '100%',
        height: 80,
        backgroundColor: '#0d5ba3',
        justifyContent: 'flex-end',
        alignItems: 'center',
        paddingBottom: 15,
    },
    tituloHeader: {
        fontSize: 26,
        fontWeight: 'bold',
        color: '#f2f7fa',
    },
    cardConteudo: {
        width: '92%',
        flex: 1,
        backgroundColor: '#e3f1ff',
        marginTop: 10,
        marginBottom: 10,
        borderRadius: 8,
        padding: 15,
        alignItems: 'center',
    },
    tagRodada: {
        backgroundColor: '#E0F7F4',
        paddingVertical: 6,
        paddingHorizontal: 18,
        borderRadius: 20,
        marginBottom: 15,
    },
    textoTagRodada: {
        color: '#0D2538',
        fontWeight: 'bold',
        fontSize: 13,
    },
    circuloSorteado: {
        width: 140,
        height: 140,
        borderRadius: 70,
        backgroundColor: '#0D2538',
        borderWidth: 6,
        borderColor: '#0b7691',
        justifyContent: 'center',
        alignItems: 'center',
    },
    labelCirculo: {
        color: '#FFFFFF',
        fontSize: 9,
        fontWeight: 'bold',
        marginBottom: 2,
    },
    numeroCirculo: {
        color: '#FFFFFF',
        fontSize: 48,
        fontWeight: 'bold',
    },
    ultimoSorteadoText: {
        color: '#777',
        fontSize: 12,
        marginVertical: 12,
    },
    containerInput: {
        width: '100%',
        marginBottom: 15,
    },
    labelInput: {
        color: '#0D2538',
        fontWeight: 'bold',
        fontSize: 13,
        marginBottom: 6,
    },
    input: {
        width: '100%',
        height: 42,
        borderWidth: 1,
        borderColor: '#0e71b3',
        borderRadius: 6,
        paddingHorizontal: 12,
        textAlign: 'center',
        color: '#333',
    },
    botaoSortear: {
        width: '100%',
        height: 42,
        backgroundColor: '#0f3261',
        borderRadius: 6,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 10,
    },
    textoBotao: {
        color: '#f8fcff',
        fontWeight: 'bold',
        fontSize: 15,
    },
    textoErro: {
        color: 'red',
        fontSize: 11,
        marginTop: 4,
        textAlign: 'center',
    },
    cardPontos: {
        width: '100%',
        height: 65,
        backgroundColor: '#EDF9F7',
        flexDirection: 'row',
        borderRadius: 4,
        marginBottom: 10,
        overflow: 'hidden',
    },
    barraVerde: {
        width: 5,
        height: '100%',
        backgroundColor: '#0a4a94',
    },
    conteudoCard: {
        paddingLeft: 12,
        justifyContent: 'center',
    },
    labelPlacar: {
        color: '#666',
        fontSize: 9,
        fontWeight: 'bold',
    },
    valorPlacar: {
        color: '#0D2538',
        fontSize: 18,
        fontWeight: 'bold',
    },
    subtextPlacar: {
        color: '#666',
        fontSize: 12,
        fontWeight: 'bold',
    },
    mensagemRodape: {
        color: '#0D2538',
        fontWeight: 'bold',
        fontSize: 14,
        marginTop: 10,
    },
    containerFim: {
        width: '90%',
        alignItems: 'center',
        paddingTop: 40,
    },
    tituloFim: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#0D2538',
        marginBottom: 30,
    },
    cardPlacarFim: {
        width: '100%',
        backgroundColor: '#EDF9F7',
        padding: 20,
        borderRadius: 8,
        alignItems: 'center',
        marginBottom: 30,
    }
});